stages:
  get_data:
    cmd: python -m src.data.get_data fiap-ds-mlops dataset/laptopPrice.csv data/raw/laptopPrice.csv
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/laptopPrice.csv

  process:
    cmd: python -m src.data.make_dataset data/raw/laptopPrice.csv data/processed/laptop-pricing.csv
    deps:
    - src/data/make_dataset.py
    - data/raw/laptopPrice.csv
    outs:
    - data/processed/laptop-pricing.csv

  train:
    cmd: python -m src.models.train_model data/processed/laptop-pricing.csv models/model.pkl
    deps:
    - src/models/train_model.py
    - data/processed/laptop-pricing.csv
    outs:
    - models/model.pkl

  test:
    cmd: python -m pytest
    deps:
    - models/model.pkl


artifacts:
  laptop-pricing-india:
    path: models/model.pkl
    desc: Modelo para predição de preços de laptops.
    type: model
    labels:
    - regression
    - pricing
    - laptop

metrics:
- dvclive/metrics.json

plots:
- dvclive/plots/metrics:
    x: step
