stages:
  process:
    cmd: python -m src.data.make_dataset data/raw/laptopPrice.csv data/processed/laptop-pricing.csv
    deps:
    - src/data/make_dataset.py
    outs:
    - data/processed/laptop-pricing.csv

  train:
    cmd: python -m src.models.train_model data/processed/laptop-pricing.csv models/model.pkl
    deps:
    - src/models/train_model.py
    - data/processed/laptop-pricing.csv
    outs:
    - models/model.pkl

artifacts:
  laptop-pricing:
    path: models/model.pkl
    type: model
    desc: Model to predict laptop pricing.
    labels:
    - regression
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
