stages:
  get_data:
    cmd: python -m src.data.get_data fiap-ds-mlops dataset/laptopPrice.csv data/raw/laptopPrice.csv
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/laptopPrice.csv

  process_dataset:
    cmd: python -m src.data.make_dataset data/raw/laptopPrice.csv data/processed/laptop-pricing.csv
    deps:
    - src/data/make_dataset.py
    - data/raw/laptopPrice.csv
    outs:
    - data/processed/laptop-pricing.csv

  process_features:
    cmd: python -m src.data.make_features data/processed/laptop-pricing.csv data/processed/laptop-pricing-features.csv
    deps:
    - src/data/make_features.py
    - data/processed/laptop-pricing.csv
    outs:
    - data/processed/laptop-pricing-features.csv

  train:
    cmd: python -m src.models.train_model data/processed/laptop-pricing-features.csv
      models/model.pkl
    deps:
    - src/models/train_model.py
    - data/processed/laptop-pricing-features.csv
    outs:
    - models/model.pkl

  test:
    cmd: python -m pytest
    deps:
    - models/model.pkl


artifacts:
  laptop-pricing-india:
    path: models/model.pkl
    desc: Modelo para predição de preços de laptops (Rupees indiano, RPI)
    type: model
    labels:
    - regression
    - pricing
    - laptop

  laptop-pricing:
    path: models/model.pkl
    type: model
    desc: Model to predict laptop pricing.
    labels:
    - regression
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
