name: Notifiy deployment of new api version

on:
  push:
    tags:
      - '*'

jobs:
  notify_api_repository:
    runs-on: ubuntu-latest

    steps:
        - run: |
            curl -X POST \
            -H "Authorization: Bearer ${{secrets.GITHUB_ACCESS_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/michelpf/fiap-ds-mlops-api-laptop-pricing/actions/workflows/deploy.yml/dispatches \
            -d '{"ref": "master"}'