name: Notifiy deployment of new api version

on:
  push:
    tags:
      - '*'

jobs:
  notify_api_repository:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Stage
        uses: actions/github-script@v5
        with:
            github-token: ${{ secrets.ACCESS_TOKEN }}
            script: |
                await github.rest.actions.createWorkflowDispatch({
                    owner: "michelpf",
                    repo: "fiap-ds-mlops-api-laptop-pricing",
                    workflow_id: "deploy.yml",
                    ref: "master"
                })