name: Avaliação de novo modelo

on: 
  pull_request:
  
jobs:
  train_evaluate_model:
    name: "Avaliação de Modelo"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write
      

    steps:
      - name: Configure Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Checkout do repositório
        uses: actions/checkout@v4
      
      - name: Configurando credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::989944764342:role/GithubActionsRole
          aws-region: us-east-1
      
      - name: Instalando dependências
        run: |
          pip install -r requirements.txt
      
      - name: Configurando DVC
        uses: iterative/setup-cml@v3

      - name: Treinamento
        run: |
          dvc pull
          dvc repro 

      - name: Geração de relatório
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --depth=1 origin master:master
          dvc metrics diff --md master >> report.md

          # Add figure to the report
          echo "![](./reports/figures/true_vs_predicted.png)" >> report.md
          cml comment create report.md

          
