name: Train the model then publish to be versioned

on: 
  push:
    branches: [ "master" ]
  
jobs:
  obtendo-artefatos:
    name: "Obtendo artefatos"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Configure Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::989944764342:role/GithubActionsRole
          aws-region: us-east-1
    
  instalando-dependencias:
    name: "Instalando dependências"
    needs: obtendo-artefatos
    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install DVC library
        uses: iterative/setup-cml@v3
  
  executando_pipeline_ml:
    name: "Executando pipeline de machine learning"
    needs: instalando-dependencias
    runs-on: ubuntu-latest
    
    steps:
      - name: Training
        run: |
          dvc pull
          dvc repro 
  
  registrando-modelo:
    name: "Registrando o modelo"
    needs: executando_pipeline_ml
    runs-on: ubuntu-latest
    
    steps:
      - name: Registering
        run: |
          git log -n 1 --pretty=format:%an    # username
          git log -n 1 --pretty=format:%ae    # email
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          gto register laptop-pricing-india
          gto assign laptop-pricing-india --stage prod
          git push origin --tags

      - name: Generating report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Model Metrics:" >> $GITHUB_STEP_SUMMARY
        
          dvc metrics show --md  >> $GITHUB_STEP_SUMMARY
          
          # Add figure to the report
          echo "![](https://raw.githubusercontent.com/michelpf/fiap-ds-mlops-laptop-pricing/master/reports/figures/true_vs_predicted.png)"  >> $GITHUB_STEP_SUMMARY

          