name: model-training
on: [push]
jobs:
  train_evaluate_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    
    permissions:
      id-token: write

    steps:
      - name: Configure Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::989944764342:role/GithubActionsRole
          aws-region: us-east-1
      
      - name: Install dependencies
        env:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
        run: |
          pip install -r requirements.txt
      
      - name: Install DVC library
        uses: iterative/setup-cml@v1

      - name: Training
        run: dvc repro 

      - name: Generating report
        run: |
          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add figure to the report
          echo "## Validating results by region"
          cml-publish ./reports/figures/true_vs_predicted.png --md >> report.md
          cml-send-comment report.md